# Installation and setup
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- name: Check if Oh My Zsh already installed
  stat: path="{{oh_my_zsh_home}}"
  register: oh_my_zsh

- debug:
    msg: "Oh My Zsh already installed"
  when: oh_my_zsh.stat.exists

- debug:
    msg: "Oh My Zsh not installed"
  when: not oh_my_zsh.stat.exists

# Oh My Zsh Installation
- import_tasks: oh_my_zsh.yml
  when: not oh_my_zsh.stat.exists

# Powerline fonts Installation
- name: Clone Powerline fonts
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: "{{powerline_fonts_home}}"
    accept_hostkey: yes
    update: yes

- name: Install Powerline fonts
  command: "{{powerline_fonts_home}}/install.sh"

# Oh My Zsh plugins
- name: Clone oh-my-zsh custom plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ oh_my_zsh_home }}/custom/plugins/{{ item.name }}"
    version: "{{ item.version }}"
    accept_hostkey: yes
    update: yes
  with_items: "{{ oh_my_zsh_custom_plugins }}"
  tags: configuration
# Oh My Zsh themes
- name: Clone oh-my-zsh custom themes
  git:
    repo: "{{ item.repo }}"
    dest: "{{ oh_my_zsh_home }}/custom/themes/{{ item.name }}"
    version: "{{ item.version }}"
    accept_hostkey: yes
    update: yes
  with_items: "{{ oh_my_zsh_custom_themes }}"
  tags: configuration

- set_fact:
    zsh_config_content: "{{ lookup('template', 'templates/zsh.config.j2') }}"

- name: Create zsh config file
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    content: "{{ zsh_config_content }}"
    marker: "## {mark} added by ansible (zsh configuration)"
    mode: 0640
  tags: configuration